apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    app: nginx-lab
spec:
  type: NodePort
  selector:
    app: nginx-lab
  ports:
    - name: http
      port: 80        # porta do Service
      targetPort: 80  # porta do container
      nodePort: 30080 # porta exposta no Node (30000–32767)

